institute/urls.py
from django.urls import path
from . import views

app_name = 'institute'

urlpatterns = [
    path('',views.institutes, name='institutes_list'),
    path('<int:id>/',views.institute_detail, name='institute_details'),
    path('add/',views.add_institute, name='add_institute'),
    path('update/<int:id>/',views.update_institute, name='update_institute'),
]

pages/urls.py
from django.urls import path
from . import views

app_name='pages'

urlpatterns = [
    path('', views.index, name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('pages.urls', namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('institute/', include('institute.urls', namespace='institutes')),
    path('assessment/', include('assessment.urls', namespace='assessment')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

institute/models.py
from django.db import models
from settings.models import City, Country, Province

b_type= [
    ('Public', 'Public'),
    ('Private', 'Private'),
]
class Institute(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    type = models.ForeignKey("InstituteType", on_delete=models.CASCADE)
    specialty = models.ForeignKey("Specialty", on_delete=models.CASCADE)
    business_type = models.CharField(choices=b_type, max_length=225)

    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True)
    province = models.ForeignKey(Province, on_delete=models.CASCADE, blank=True, null=True)    
    city = models.ForeignKey(City, on_delete=models.CASCADE, blank=True, null=True)
    img = models.ImageField(upload_to="institute/", blank=True, null=True)

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    class Meta:
        unique_together = ('name','country')

    def __str__(self):
        return self.name
    
class InstituteType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Specialty(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "Specialties"

    def __str__(self):
        return self.name

institute/forms.py
from django import forms
from .models import Institute
from settings.models import City, Province, Country


class AddInstituteForm(forms.ModelForm):
    class Meta:
        model = Institute
        fields = '__all__'
        exclude = ['created_at', 'updated_at']
    
class UpdateInstituteForm(forms.ModelForm):
    class Meta:
        model = Institute
        fields = '__all__'
        exclude = ['created_at', 'updated_at']

institute/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from institute.models import Institute
from settings.models import City, Country, Province

from .forms import AddInstituteForm, UpdateInstituteForm

def institutes(request):
    institutes_list = Institute.objects.all()
    num_of_institutes = institutes_list.count()
    paginator = Paginator(institutes_list, 5) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)    

    context = {
        'institutes_list': page_obj, 
        'num_of_institutes':num_of_institutes,
    }
    return render(request, 'institute/institutes.html', context)

def institute_detail(request, id):
    institute = Institute.objects.get(id=id)
    context = {
        'institute' : institute,
    }
    return render(request, 'institute/institute_details.html', context)

@login_required
def add_institute(request):
    if request.method == "POST":
        form = AddInstituteForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            message = "The institute has been added sucessfully!"
            messages.add_message(request, messages.INFO, message)
            return redirect(reverse("institute:institutes_list"))
        else:
            message = "There was something wrong, please double check your entried data!"
            messages.add_message(request, messages.INFO, message)
    else:
        form = AddInstituteForm()
    
    context = {'form' : form }
    return render(request, 'institute/add_institute.html', context)

@login_required
def update_institute(request, id):
    instance = Institute.objects.get(id=id)
    if request.method == "POST":
        form = UpdateInstituteForm(request.POST or None, request.FILES or None, instance=instance)
        if form.is_valid():
            form.save()
            message = "The institute has been updated sucessfully!"
            messages.add_message(request, messages.SUCCESS, message)
            return redirect("/institute/"+str(id))
        else:
            message = "There was something wrong, please double check your entried data!"
            messages.add_message(request, messages.WARNING, message)
    else:
        form = UpdateInstituteForm(instance=instance)

    context = {'form':form}
    return render(request, 'institute/update_institute.html', context)

institute/templates/institute/add_institute.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}
{% block title %}Add Institue{% endblock title %}

{% block content %}


  <strong>Add an institute</strong>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Add" class="boxed-btn4"/>
  </form>

{% endblock %}

institute/templates/institute/institute_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detials{% endblock title %}
{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{institute.name}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                {% if institute.img %}
                                    <img src="{{institute.img.url}}" class="institute-list" alt="">
                                {% else %}
                                    <img src="{% static 'img/institution-icon-3.png' %}" class="institute-list" alt="">
                                {% endif %}
                            </div>
                            <div class="jobs_conetent">
                                <a href="#"><h4>{{institute}}</h4></a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> {{institute.city}}/{{institute.city.province.country}}</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> {{institute.type}}/{{institute.business_type}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                        -->
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        {% include 'messages.html' %}
                        <h4>Description</h4>
                        <p>{{institute.description}}</p>
                    </div>
                    <div class="p-5">
                        <a href="{% url 'institute:update_institute' institute.id %}" class="boxed-btn4">Edit Institue</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Added on: <span>{{institute.created_at}}</span></li>
                            <li>Type: <span>{{institute.type}}</span></li>
                            <li>Specialty: <span>{{institute.specialty}}</span></li>
                            <li>Business Type: <span>{{institute.business_type}}</span></li>
                            <li>City: <span>{{institute.city}}</span></li>
                            <li>Province: <span>{{institute.city.province}}</span></li>
                            <li>Country: <span>{{institute.city.province.country}}</span></li>
                            <li>Region: <span>{{institute.city.province.country.continent}}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Share at:</span>
                    <ul>
                        <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                          function initMap() {
                            var uluru = {lat: -25.363, lng: 131.044};
                            var grayStyles = [
                              {
                                featureType: "all",
                                stylers: [
                                  { saturation: -90 },
                                  { lightness: 50 }
                                ]
                              },
                              {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                            ];
                            var map = new google.maps.Map(document.getElementById('map'), {
                              center: {lat: -31.197, lng: 150.744},
                              zoom: 9,
                              styles: grayStyles,
                              scrollwheel:  false
                            });
                          }
                          
                        </script>
                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                        
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

institute/templates/institute/institutes.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Institutes{% endblock title %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>+{{num_of_institutes}} Higher-Education Institutes Added</h3>
                        <h4>With Statistics of Sustainability Reportings Available</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form action="#">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <input type="text" placeholder="Search keyword">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Location">Location</option>
                                                <option value="1">Rangpur</option>
                                                <option value="2">Dhaka </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Category">Category</option>
                                                <option value="1">Category 1</option>
                                                <option value="2">Category 2 </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Experience">Experience</option>
                                                <option value="1">Experience 1</option>
                                                <option value="2">Experience 2 </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Job type">Job type</option>
                                                <option value="1">full time 1</option>
                                                <option value="2">part time 2 </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Qualification">Qualification</option>
                                                <option value="1">Qualification 1</option>
                                                <option value="2">Qualification 2</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Gender">Gender</option>
                                                <option value="1">male</option>
                                                <option value="2">female</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="range_wrap">
                            <label for="amount">Price range:</label>
                            <div id="slider-range"></div>
                            <p>
                                <input type="text" id="amount" readonly style="border:0; color:#7A838B; font-size: 14px; font-weight:400;">
                            </p>
                        </div>
                        <div class="reset_btn">
                            <button  class="boxed-btn3 w-100" type="submit">Reset</button>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% include 'messages.html' %}
                            {% for institute in institutes_list %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            {% if institute.img %}
                                                <img src="{{institute.img.url}}" class="institute-list" alt="">
                                            {% else %}
                                                <img src="{% static 'img/institution-icon-3.png' %}" class="institute-list" alt="">
                                            {% endif %}
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'institutes:institute_details' institute.id %}"><h4>{{institute}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i>{{institute.city}}/{{institute.city.province.country}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{institute.type}}/{{institute.business_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <!--<a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a> -->
                                            <a href="#" class="boxed-btn3">Check</a>
                                        </div>
                                        <!--
                                        <div class="date">
                                            <p>Date line: 31 Jan 2020</p>
                                        </div>
                                        -->
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if institutes_list.has_previous %}
                                            <li><a href="?page={{institutes_list.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        {% for i in institutes_list.paginator.page_range %}
                                            {% if institutes_list.number == i %}
                                                <li><a href="#"><span>{{i}}</span></a></li>
                                            {% else %}
                                                <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if institutes_list.has_next %}
                                            <li><a href="?page={{institutes_list.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

{% endblock %}

institute/templates/institute/update_institute.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}

{% block content %}


  <strong>Update an institute</strong>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Update" class="boxed-btn4"/>
  </form>

{% endblock %}